### ISSUE TITLE
Get class names for non-eng courses

### ISSUE THREAD

**Issue by CarsonCook** [QueensEngineeringSociety/QLife#25]
Only eng course names are retrieved right now

**Comment by ruffoa** [comment]
Should be possible for most other faculties, but currently impossible without a dedicated database for Commerce courses, due to the way that their website was designed (can't parse the information out)

**Comment by ruffoa** [comment]
Turns out most other faculties use a pdf for the course lists, so this may be impossible without a dedicated database hosted somewhere that gets downloaded to the phone.  ArtSci's list for example is a 8MB(!) PDF file
